# Generated by Django 3.0.2 on 2020-03-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200327_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designpatentinfo',
            name='pub_date',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='markpatentinfo',
            name='pub_date',
            field=models.CharField(max_length=64),
        ),
    ]
