# Generated by Django 3.0.2 on 2020-03-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPatentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_num', models.CharField(max_length=64)),
                ('app_name', models.CharField(max_length=64)),
                ('agent_name', models.CharField(max_length=64)),
                ('app_status', models.CharField(max_length=64)),
                ('pub_date', models.DateField()),
                ('pub_num', models.CharField(max_length=64)),
                ('image_path', models.URLField()),
                ('article_name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarkPatentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_num', models.CharField(max_length=64)),
                ('app_name', models.CharField(max_length=64)),
                ('agent_name', models.CharField(max_length=64)),
                ('app_status', models.CharField(max_length=64)),
                ('pub_date', models.DateField()),
                ('pub_num', models.CharField(max_length=64)),
                ('image_path', models.URLField()),
                ('title', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
