# Generated by Django 3.0.2 on 2020-05-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200327_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markpatentinfo',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
